[sources.docker]
type = "docker_logs"
docker_host = "/var/run/docker.sock"
exclude_containers = ["grafana", "prometheus", "cadvisor", "node-exporter", "loki", "vector"]

[transforms.add_service_label]
type   = "remap"
inputs = ["docker"]
source = '''
.service = .label."com.docker.compose.service"
if is_null(.service) {
  .service = .container_name
  if is_null(.service) { .service = "unknown" }
}
'''

[sinks.loki]
type = "loki"
inputs = ["add_service_label"]
endpoint = "http://loki:3100"
encoding.codec = "json"
healthcheck.enabled = true

labels.service   = "{{ service }}"
labels.container = "{{ container_name }}"
